version: "3"

services:

  # Database
  db-postgres:
    image: postgres:9.6.24
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: "321654987"
      # POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=pt_BR.UTF-8 --lc-ctype=pt_BR.UTF-8'
    ports:
      - 5432:5432
    volumes:
      - /var/www/docker/volumes/postgres:/var/lib/postgresql/data
    networks:
      - net-db-postgres
  
  # Admin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "farias.softwares@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "321654987"
    ports:
      - 16543:80
    depends_on:
      - db-postgres
    volumes:
      - vol-pgadmin:/var/lib/pgadmin
    networks:
      - net-db-postgres

volumes:
  vol-pgadmin:

networks: 
  net-db-postgres:
    driver: bridge
  
